In [6]:
import numpy as np
import scipy as sp
import tensorly as tn

In [46]:
def get_strassen_tensor():
    # могу представить в виде 8 разложимых тензоров
    tensor = np.zeros((2, 2, 2, 2, 2, 2))
    tensor[0, 0, 0, 0, 0, 0] = 1
    tensor[0, 1, 1, 0, 0, 0] = 1
    tensor[0, 0, 0, 1, 0, 1] = 1
    tensor[0, 1, 1, 1, 0, 1] = 1
    tensor[1, 0, 0, 0, 1, 0] = 1
    tensor[1, 1, 1, 0, 1, 0] = 1
    tensor[1, 0, 0, 1, 1, 1] = 1
    tensor[1, 1, 1, 1, 1, 1] = 1
    return np.reshape(tensor, (4, 4, 4))

def get_kronecer_symbol(i, j, k, l, m, n):
    return int((i == m) and (j == k) and (l == n))

def get_tensor():
    tensor = np.fromfunction(np.vectorize(get_kronecer_symbol), (2, 2, 2, 2, 2, 2))
    return np.reshape(tensor, (4, 4, 4))

In [57]:
tensor = get_tensor()
print(tensor)

[[[1 0 0 0]
  [0 1 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [1 0 0 0]
  [0 1 0 0]]

 [[0 0 1 0]
  [0 0 0 1]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 1 0]
  [0 0 0 1]]]


In [58]:
canonical_repr = tn.decomposition.parafac(tensor, 7)
print(len(canonical_repr.factors))

LinAlgError: Singular matrix